apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventofcode-solver-2023
  namespace: adventofcode
spec:
  selector:
    matchLabels:
      app: adventofcode-solver-2023
  replicas: 2
  template:
    metadata:
      labels:
        app: adventofcode-solver-2023
    spec:
      nodeName: klust1
      containers:
        - name: adventofcode
          image: registry.brotherlogic-backend.com/brotherlogic/adventofcode-solver-2023:0.297.0 # {"$imagepolicy": "flux-system:adventofcode-solver-2023"}
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adventofcode-solver-2023
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - adventofcode
  selector:
    matchLabels:
      app: adventofcode-solver-2023
---
apiVersion: v1
kind: Service
metadata:
  name: adventofcode-solver-2023
  namespace: adventofcode
  labels:
    app: adventofcode-solver-2023
spec:
  type: NodePort
  metadata:
    labels:
      app: adventofcode-solver-2023
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
  selector:
    app: adventofcode-solver-2023
