# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: advent.proto for package 'adventofcode'

require 'grpc'
require 'advent_pb'

module Adventofcode
  module AdventOfCodeService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'adventofcode.AdventOfCodeService'

      rpc :Solve, ::Adventofcode::SolveRequest, ::Adventofcode::SolveResponse
    end

    Stub = Service.rpc_stub_class
  end
  module AdventOfCodeInternalService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'adventofcode.AdventOfCodeInternalService'

      rpc :Upload, ::Adventofcode::UploadRequest, ::Adventofcode::UploadResponse
      rpc :Register, ::Adventofcode::RegisterRequest, ::Adventofcode::RegisterResponse
      rpc :AddSolution, ::Adventofcode::AddSolutionRequest, ::Adventofcode::AddSolutionResponse
      rpc :GetSolution, ::Adventofcode::GetSolutionRequest, ::Adventofcode::GetSolutionResponse
      rpc :SetCookie, ::Adventofcode::SetCookieRequest, ::Adventofcode::SetCookieResponse
    end

    Stub = Service.rpc_stub_class
  end
  module SolverService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'adventofcode.SolverService'

      rpc :Solve, ::Adventofcode::SolveRequest, ::Adventofcode::SolveResponse
    end

    Stub = Service.rpc_stub_class
  end
end
