apiVersion: batch/v1
kind: CronJob
metadata:
  name: adventofcode-finder
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: adventofcode-finder
              image: registry.brotherlogic-backend.com/brotherlogic/adventofcode-finder:0.217.0 # {"$imagepolicy": "flux-system:adventofcode-finder"}
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
