apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventofcode
  namespace: adventofcode
spec:
  selector:
    matchLabels:
      app: adventofcode
  replicas: 2
  template:
    metadata:
      labels:
        app: adventofcode
    spec:
      containers:
      - name: adventofcode
        image: registry.brotherlogic-backend.com/brotherlogic/adventofcode:0.49.0 # {"$imagepolicy": "flux-system:adventofcode"}
        ports:
        - containerPort: 8080
       volumes:
        - name: serverpem-vol
          secret:
            secretName: serverpem
        - name: serverkey-vol
          secret:
            secretName: serverkey
      imagePullSecrets:
      - name: regcred
