apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventofcode
  namespace: adventofcode
spec:
  selector:
    matchLabels:
      app: adventofcode
  replicas: 2
  template:
    metadata:
      labels:
        app: adventofcode
    spec:
      containers:
      - name: adventofcode
        image: registry.brotherlogic-backend.com/brotherlogic/adventofcode:0.51.0 # {"$imagepolicy": "flux-system:adventofcode"}
        ports:
        - containerPort: 8080
        volumeMounts:
         - name: serverpem-vol
           mountPath: "/"
           readOnly: true
         - name: serverkey-vol
           mountPath: "/"
           readOnly: true
         - name: cacertpem-vol
           mountPath: "/" 
           readOnly: true
      volumes:
      - name: serverpem-vol
        secret:
          secretName: serverpem
      - name: serverkey-vol
        secret:
          secretName: serverkey
      - name: cacertpem-vol
        secret:
          secretName: cacertpem
      imagePullSecrets:
      - name: regcred
