apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventofcode
  namespace: adventofcode
spec:
  selector:
    matchLabels:
      app: adventofcode
  replicas: 2
  template:
    metadata:
      labels:
        app: adventofcode
    spec:
      containers:
      - name: adventofcode
        image: registry.brotherlogic-backend.com/brotherlogic/adventofcode:0.68.0 # {"$imagepolicy": "flux-system:adventofcode"}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: serverpem-vol
          mountPath: "/sp"
          readOnly: true
        - name: serverkey-vol
          mountPath: "/sk"
          readOnly: true
        - name: cacertpem-vol
          mountPath: "/cp"
          readOnly: true
      volumes:
      - name: serverpem-vol
        secret:
          secretName: serverpem
      - name: serverkey-vol
        secret:
          secretName: serverkey
      - name: cacertpem-vol
        secret:
          secretName: cacertpem
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: adventofcode
  namespace: adventofcode
  labels:
    app: adventofcode
  annotations:
    traefik.ingress.kuberentes.io/service.serversscheme: h2c
spec:
  metadata:
    labels:
      app: adventofcode
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: adventofcode
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adventofcode
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - adventofcode
  selector:
    matchLabels:
      app: adventofcode
