apiVersion: v1
kind: Service
metadata:
  name: adventofcode
  namespace: adventofcode
spec:
  type: NodePort
  metadata:
    annotations:
      prometheus.io/port: "8081"
      prometheus.io/scrape: "true"
    labels:
      app: adventofcode
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: adventofcode