apiVersion: v1
kind: Service
metadata:
  name: adventofcode
  namespace: adventofcode
  labels:
    app: adventofcode
  annotations:
    traefik.ingress.kuberentes.io/service.serversscheme: h2c
spec:
  metadata:
    labels:
      app: adventofcode
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: adventofcode
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adventofcode
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
    - adventofcode
  selector:
    matchLabels:
      app: adventofcode