apiVersion: v1
kind: Service
metadata:
  name: adventofcode
  namespace: adventofcode
  labels:
    app: adventofcode
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: adventofcode