apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: adventofcode
  namespace: adventofcode
spec:
  image: registry.brotherlogic-backend.com/brotherlogic/adventofcode
  interval: 1m0s
  secretRef:
    name: regcred
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: adventofcode
  namespace: adventofcode
spec:
  imageRepositoryRef:
    name: adventofcode
  policy:
    semver:
      range: 0.x.0
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: adventofcode
  namespace:  adventofcode
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: adventofcode
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./deployment/
    strategy: Setters
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: adventofcode
  namespace: adventofcode
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/brotherlogic/adventofcode

