apiVersion: v1
kind: Service
metadata:
  name: adventofcode
  namespace: adventofcode
  labels:
    app: adventofcode
spec:
  type: NodePort
  metadata:
    labels:
      app: adventofcode
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
    - name: internal-grpc
      port: 8082
      targetPort: 8082
  selector:
    app: adventofcode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventofcode-solver-2015
  namespace: adventofcode
spec:
  selector:
    matchLabels:
      app: adventofcode-solver-2015
  replicas: 2
  template:
    metadata:
      labels:
        app: adventofcode-solver-2015
    spec:
      containers:
      - name: adventofcode
        image: registry.brotherlogic-backend.com/brotherlogic/adventofcode-solver-2015:0.84.0 # {"$imagepolicy": "flux-system:adventofcode-solver-2015"}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adventofcode-solver-2015
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - adventofcode
  selector:
    matchLabels:
      app: adventofcode-solver-2015
