// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: advent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Issue struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SolutionAttempts []*Solution            `protobuf:"bytes,2,rep,name=solution_attempts,json=solutionAttempts,proto3" json:"solution_attempts,omitempty"`
	Open             bool                   `protobuf:"varint,3,opt,name=open,proto3" json:"open,omitempty"`
	Year             int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Day              int32                  `protobuf:"varint,5,opt,name=day,proto3" json:"day,omitempty"`
	Part             int32                  `protobuf:"varint,6,opt,name=part,proto3" json:"part,omitempty"`
	LastErrorCode    string                 `protobuf:"bytes,7,opt,name=last_error_code,json=lastErrorCode,proto3" json:"last_error_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_advent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{0}
}

func (x *Issue) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Issue) GetSolutionAttempts() []*Solution {
	if x != nil {
		return x.SolutionAttempts
	}
	return nil
}

func (x *Issue) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *Issue) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Issue) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Issue) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

func (x *Issue) GetLastErrorCode() string {
	if x != nil {
		return x.LastErrorCode
	}
	return ""
}

type Solutions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solutions     []*Solution            `protobuf:"bytes,1,rep,name=solutions,proto3" json:"solutions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Solutions) Reset() {
	*x = Solutions{}
	mi := &file_advent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Solutions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solutions) ProtoMessage() {}

func (x *Solutions) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solutions.ProtoReflect.Descriptor instead.
func (*Solutions) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{1}
}

func (x *Solutions) GetSolutions() []*Solution {
	if x != nil {
		return x.Solutions
	}
	return nil
}

type Solution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Day           int32                  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Part          int32                  `protobuf:"varint,3,opt,name=part,proto3" json:"part,omitempty"`
	BigAnswer     int64                  `protobuf:"varint,4,opt,name=big_answer,json=bigAnswer,proto3" json:"big_answer,omitempty"`
	StringAnswer  string                 `protobuf:"bytes,5,opt,name=string_answer,json=stringAnswer,proto3" json:"string_answer,omitempty"`
	Answer        int32                  `protobuf:"varint,6,opt,name=answer,proto3" json:"answer,omitempty"`
	SolutionMade  int64                  `protobuf:"varint,7,opt,name=solution_made,json=solutionMade,proto3" json:"solution_made,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Solution) Reset() {
	*x = Solution{}
	mi := &file_advent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Solution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solution) ProtoMessage() {}

func (x *Solution) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solution.ProtoReflect.Descriptor instead.
func (*Solution) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{2}
}

func (x *Solution) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Solution) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Solution) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

func (x *Solution) GetBigAnswer() int64 {
	if x != nil {
		return x.BigAnswer
	}
	return 0
}

func (x *Solution) GetStringAnswer() string {
	if x != nil {
		return x.StringAnswer
	}
	return ""
}

func (x *Solution) GetAnswer() int32 {
	if x != nil {
		return x.Answer
	}
	return 0
}

func (x *Solution) GetSolutionMade() int64 {
	if x != nil {
		return x.SolutionMade
	}
	return 0
}

type SolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Day           int32                  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Part          int32                  `protobuf:"varint,3,opt,name=part,proto3" json:"part,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolveRequest) Reset() {
	*x = SolveRequest{}
	mi := &file_advent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveRequest) ProtoMessage() {}

func (x *SolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveRequest.ProtoReflect.Descriptor instead.
func (*SolveRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{3}
}

func (x *SolveRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *SolveRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *SolveRequest) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

func (x *SolveRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        int32                  `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	StringAnswer  string                 `protobuf:"bytes,2,opt,name=string_answer,json=stringAnswer,proto3" json:"string_answer,omitempty"`
	BigAnswer     int64                  `protobuf:"varint,3,opt,name=big_answer,json=bigAnswer,proto3" json:"big_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolveResponse) Reset() {
	*x = SolveResponse{}
	mi := &file_advent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolveResponse) ProtoMessage() {}

func (x *SolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolveResponse.ProtoReflect.Descriptor instead.
func (*SolveResponse) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{4}
}

func (x *SolveResponse) GetAnswer() int32 {
	if x != nil {
		return x.Answer
	}
	return 0
}

func (x *SolveResponse) GetStringAnswer() string {
	if x != nil {
		return x.StringAnswer
	}
	return ""
}

func (x *SolveResponse) GetBigAnswer() int64 {
	if x != nil {
		return x.BigAnswer
	}
	return 0
}

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Day           int32                  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	DualDay       bool                   `protobuf:"varint,4,opt,name=dual_day,json=dualDay,proto3" json:"dual_day,omitempty"`
	Part          int32                  `protobuf:"varint,5,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_advent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{5}
}

func (x *UploadRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UploadRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *UploadRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UploadRequest) GetDualDay() bool {
	if x != nil {
		return x.DualDay
	}
	return false
}

func (x *UploadRequest) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_advent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{6}
}

type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Day           int32                  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Part          int32                  `protobuf:"varint,3,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_advent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{7}
}

func (x *GetDataRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetDataRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *GetDataRequest) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

type GetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_advent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{8}
}

func (x *GetDataResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Callback      string                 `protobuf:"bytes,1,opt,name=callback,proto3" json:"callback,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	StartupTime   int64                  `protobuf:"varint,3,opt,name=startup_time,json=startupTime,proto3" json:"startup_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_advent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterRequest) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *RegisterRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RegisterRequest) GetStartupTime() int64 {
	if x != nil {
		return x.StartupTime
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_advent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{10}
}

type AddSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solution      *Solution              `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSolutionRequest) Reset() {
	*x = AddSolutionRequest{}
	mi := &file_advent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSolutionRequest) ProtoMessage() {}

func (x *AddSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSolutionRequest.ProtoReflect.Descriptor instead.
func (*AddSolutionRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{11}
}

func (x *AddSolutionRequest) GetSolution() *Solution {
	if x != nil {
		return x.Solution
	}
	return nil
}

type AddSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSolutionResponse) Reset() {
	*x = AddSolutionResponse{}
	mi := &file_advent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSolutionResponse) ProtoMessage() {}

func (x *AddSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSolutionResponse.ProtoReflect.Descriptor instead.
func (*AddSolutionResponse) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{12}
}

type GetSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Day           int32                  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Part          int32                  `protobuf:"varint,3,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSolutionRequest) Reset() {
	*x = GetSolutionRequest{}
	mi := &file_advent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSolutionRequest) ProtoMessage() {}

func (x *GetSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSolutionRequest.ProtoReflect.Descriptor instead.
func (*GetSolutionRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{13}
}

func (x *GetSolutionRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetSolutionRequest) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *GetSolutionRequest) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

type GetSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solution      *Solution              `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSolutionResponse) Reset() {
	*x = GetSolutionResponse{}
	mi := &file_advent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSolutionResponse) ProtoMessage() {}

func (x *GetSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSolutionResponse.ProtoReflect.Descriptor instead.
func (*GetSolutionResponse) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{14}
}

func (x *GetSolutionResponse) GetSolution() *Solution {
	if x != nil {
		return x.Solution
	}
	return nil
}

type SetCookieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookie        string                 `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCookieRequest) Reset() {
	*x = SetCookieRequest{}
	mi := &file_advent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCookieRequest) ProtoMessage() {}

func (x *SetCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCookieRequest.ProtoReflect.Descriptor instead.
func (*SetCookieRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{15}
}

func (x *SetCookieRequest) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

type SetCookieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCookieResponse) Reset() {
	*x = SetCookieResponse{}
	mi := &file_advent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCookieResponse) ProtoMessage() {}

func (x *SetCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCookieResponse.ProtoReflect.Descriptor instead.
func (*SetCookieResponse) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{16}
}

type GetSolversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSolversRequest) Reset() {
	*x = GetSolversRequest{}
	mi := &file_advent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSolversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSolversRequest) ProtoMessage() {}

func (x *GetSolversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSolversRequest.ProtoReflect.Descriptor instead.
func (*GetSolversRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{17}
}

type GetSolversResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Years           []int32                `protobuf:"varint,1,rep,packed,name=years,proto3" json:"years,omitempty"`
	ServerStartTime int64                  `protobuf:"varint,2,opt,name=server_start_time,json=serverStartTime,proto3" json:"server_start_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSolversResponse) Reset() {
	*x = GetSolversResponse{}
	mi := &file_advent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSolversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSolversResponse) ProtoMessage() {}

func (x *GetSolversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSolversResponse.ProtoReflect.Descriptor instead.
func (*GetSolversResponse) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{18}
}

func (x *GetSolversResponse) GetYears() []int32 {
	if x != nil {
		return x.Years
	}
	return nil
}

func (x *GetSolversResponse) GetServerStartTime() int64 {
	if x != nil {
		return x.ServerStartTime
	}
	return 0
}

var File_advent_proto protoreflect.FileDescriptor

const file_advent_proto_rawDesc = "" +
	"\n" +
	"\fadvent.proto\x12\fadventofcode\"\xd2\x01\n" +
	"\x05Issue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12C\n" +
	"\x11solution_attempts\x18\x02 \x03(\v2\x16.adventofcode.SolutionR\x10solutionAttempts\x12\x12\n" +
	"\x04open\x18\x03 \x01(\bR\x04open\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x10\n" +
	"\x03day\x18\x05 \x01(\x05R\x03day\x12\x12\n" +
	"\x04part\x18\x06 \x01(\x05R\x04part\x12&\n" +
	"\x0flast_error_code\x18\a \x01(\tR\rlastErrorCode\"A\n" +
	"\tSolutions\x124\n" +
	"\tsolutions\x18\x01 \x03(\v2\x16.adventofcode.SolutionR\tsolutions\"\xc5\x01\n" +
	"\bSolution\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\x12\x12\n" +
	"\x04part\x18\x03 \x01(\x05R\x04part\x12\x1d\n" +
	"\n" +
	"big_answer\x18\x04 \x01(\x03R\tbigAnswer\x12#\n" +
	"\rstring_answer\x18\x05 \x01(\tR\fstringAnswer\x12\x16\n" +
	"\x06answer\x18\x06 \x01(\x05R\x06answer\x12#\n" +
	"\rsolution_made\x18\a \x01(\x03R\fsolutionMade\"\\\n" +
	"\fSolveRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\x12\x12\n" +
	"\x04part\x18\x03 \x01(\x05R\x04part\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"k\n" +
	"\rSolveResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\x05R\x06answer\x12#\n" +
	"\rstring_answer\x18\x02 \x01(\tR\fstringAnswer\x12\x1d\n" +
	"\n" +
	"big_answer\x18\x03 \x01(\x03R\tbigAnswer\"x\n" +
	"\rUploadRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x19\n" +
	"\bdual_day\x18\x04 \x01(\bR\adualDay\x12\x12\n" +
	"\x04part\x18\x05 \x01(\x05R\x04part\"\x10\n" +
	"\x0eUploadResponse\"J\n" +
	"\x0eGetDataRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\x12\x12\n" +
	"\x04part\x18\x03 \x01(\x05R\x04part\"%\n" +
	"\x0fGetDataResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"d\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bcallback\x18\x01 \x01(\tR\bcallback\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12!\n" +
	"\fstartup_time\x18\x03 \x01(\x03R\vstartupTime\"\x12\n" +
	"\x10RegisterResponse\"H\n" +
	"\x12AddSolutionRequest\x122\n" +
	"\bsolution\x18\x01 \x01(\v2\x16.adventofcode.SolutionR\bsolution\"\x15\n" +
	"\x13AddSolutionResponse\"N\n" +
	"\x12GetSolutionRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\x12\x12\n" +
	"\x04part\x18\x03 \x01(\x05R\x04part\"I\n" +
	"\x13GetSolutionResponse\x122\n" +
	"\bsolution\x18\x01 \x01(\v2\x16.adventofcode.SolutionR\bsolution\"*\n" +
	"\x10SetCookieRequest\x12\x16\n" +
	"\x06cookie\x18\x01 \x01(\tR\x06cookie\"\x13\n" +
	"\x11SetCookieResponse\"\x13\n" +
	"\x11GetSolversRequest\"V\n" +
	"\x12GetSolversResponse\x12\x14\n" +
	"\x05years\x18\x01 \x03(\x05R\x05years\x12*\n" +
	"\x11server_start_time\x18\x02 \x01(\x03R\x0fserverStartTime2Y\n" +
	"\x13AdventOfCodeService\x12B\n" +
	"\x05Solve\x12\x1a.adventofcode.SolveRequest\x1a\x1b.adventofcode.SolveResponse\"\x002\x80\x04\n" +
	"\x1bAdventOfCodeInternalService\x12E\n" +
	"\x06Upload\x12\x1b.adventofcode.UploadRequest\x1a\x1c.adventofcode.UploadResponse\"\x00\x12K\n" +
	"\bRegister\x12\x1d.adventofcode.RegisterRequest\x1a\x1e.adventofcode.RegisterResponse\"\x00\x12T\n" +
	"\vAddSolution\x12 .adventofcode.AddSolutionRequest\x1a!.adventofcode.AddSolutionResponse\"\x00\x12T\n" +
	"\vGetSolution\x12 .adventofcode.GetSolutionRequest\x1a!.adventofcode.GetSolutionResponse\"\x00\x12N\n" +
	"\tSetCookie\x12\x1e.adventofcode.SetCookieRequest\x1a\x1f.adventofcode.SetCookieResponse\"\x00\x12Q\n" +
	"\n" +
	"GetSolvers\x12\x1f.adventofcode.GetSolversRequest\x1a .adventofcode.GetSolversResponse\"\x002S\n" +
	"\rSolverService\x12B\n" +
	"\x05Solve\x12\x1a.adventofcode.SolveRequest\x1a\x1b.adventofcode.SolveResponse\"\x00B;Z*github.com/brotherlogic/adventofcode/proto\xaa\x02\fAdventOfCodeb\x06proto3"

var (
	file_advent_proto_rawDescOnce sync.Once
	file_advent_proto_rawDescData []byte
)

func file_advent_proto_rawDescGZIP() []byte {
	file_advent_proto_rawDescOnce.Do(func() {
		file_advent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_advent_proto_rawDesc), len(file_advent_proto_rawDesc)))
	})
	return file_advent_proto_rawDescData
}

var file_advent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_advent_proto_goTypes = []any{
	(*Issue)(nil),               // 0: adventofcode.Issue
	(*Solutions)(nil),           // 1: adventofcode.Solutions
	(*Solution)(nil),            // 2: adventofcode.Solution
	(*SolveRequest)(nil),        // 3: adventofcode.SolveRequest
	(*SolveResponse)(nil),       // 4: adventofcode.SolveResponse
	(*UploadRequest)(nil),       // 5: adventofcode.UploadRequest
	(*UploadResponse)(nil),      // 6: adventofcode.UploadResponse
	(*GetDataRequest)(nil),      // 7: adventofcode.GetDataRequest
	(*GetDataResponse)(nil),     // 8: adventofcode.GetDataResponse
	(*RegisterRequest)(nil),     // 9: adventofcode.RegisterRequest
	(*RegisterResponse)(nil),    // 10: adventofcode.RegisterResponse
	(*AddSolutionRequest)(nil),  // 11: adventofcode.AddSolutionRequest
	(*AddSolutionResponse)(nil), // 12: adventofcode.AddSolutionResponse
	(*GetSolutionRequest)(nil),  // 13: adventofcode.GetSolutionRequest
	(*GetSolutionResponse)(nil), // 14: adventofcode.GetSolutionResponse
	(*SetCookieRequest)(nil),    // 15: adventofcode.SetCookieRequest
	(*SetCookieResponse)(nil),   // 16: adventofcode.SetCookieResponse
	(*GetSolversRequest)(nil),   // 17: adventofcode.GetSolversRequest
	(*GetSolversResponse)(nil),  // 18: adventofcode.GetSolversResponse
}
var file_advent_proto_depIdxs = []int32{
	2,  // 0: adventofcode.Issue.solution_attempts:type_name -> adventofcode.Solution
	2,  // 1: adventofcode.Solutions.solutions:type_name -> adventofcode.Solution
	2,  // 2: adventofcode.AddSolutionRequest.solution:type_name -> adventofcode.Solution
	2,  // 3: adventofcode.GetSolutionResponse.solution:type_name -> adventofcode.Solution
	3,  // 4: adventofcode.AdventOfCodeService.Solve:input_type -> adventofcode.SolveRequest
	5,  // 5: adventofcode.AdventOfCodeInternalService.Upload:input_type -> adventofcode.UploadRequest
	9,  // 6: adventofcode.AdventOfCodeInternalService.Register:input_type -> adventofcode.RegisterRequest
	11, // 7: adventofcode.AdventOfCodeInternalService.AddSolution:input_type -> adventofcode.AddSolutionRequest
	13, // 8: adventofcode.AdventOfCodeInternalService.GetSolution:input_type -> adventofcode.GetSolutionRequest
	15, // 9: adventofcode.AdventOfCodeInternalService.SetCookie:input_type -> adventofcode.SetCookieRequest
	17, // 10: adventofcode.AdventOfCodeInternalService.GetSolvers:input_type -> adventofcode.GetSolversRequest
	3,  // 11: adventofcode.SolverService.Solve:input_type -> adventofcode.SolveRequest
	4,  // 12: adventofcode.AdventOfCodeService.Solve:output_type -> adventofcode.SolveResponse
	6,  // 13: adventofcode.AdventOfCodeInternalService.Upload:output_type -> adventofcode.UploadResponse
	10, // 14: adventofcode.AdventOfCodeInternalService.Register:output_type -> adventofcode.RegisterResponse
	12, // 15: adventofcode.AdventOfCodeInternalService.AddSolution:output_type -> adventofcode.AddSolutionResponse
	14, // 16: adventofcode.AdventOfCodeInternalService.GetSolution:output_type -> adventofcode.GetSolutionResponse
	16, // 17: adventofcode.AdventOfCodeInternalService.SetCookie:output_type -> adventofcode.SetCookieResponse
	18, // 18: adventofcode.AdventOfCodeInternalService.GetSolvers:output_type -> adventofcode.GetSolversResponse
	4,  // 19: adventofcode.SolverService.Solve:output_type -> adventofcode.SolveResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_advent_proto_init() }
func file_advent_proto_init() {
	if File_advent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_advent_proto_rawDesc), len(file_advent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_advent_proto_goTypes,
		DependencyIndexes: file_advent_proto_depIdxs,
		MessageInfos:      file_advent_proto_msgTypes,
	}.Build()
	File_advent_proto = out.File
	file_advent_proto_goTypes = nil
	file_advent_proto_depIdxs = nil
}
