# day7_spec.rb
require 'rspec'
require_relative 'day8'
require_relative 'lib/advent_pb'

RSpec.describe Day8 do
  describe "part 1" do
    it "returns 14" do
      day8 = Day8.new
      data = "............
      ........0...
      .....0......
      .......0....
      ....0.......
      ......A.....
      ............
      ............
      ........A...
      .........A..
      ............
      ............"
      expect(day8.solvePart1(Adventofcode::SolveRequest.new(data: data))).to eq(14)
    end
  end
end