name: test2023

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test2023:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./solvers/2023

    steps:
    - uses: actions/checkout@v2
    - name: Prep
      run:  apt-get update && apt-get install -y protobuf-compiler libprotobuf-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose